import { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { Loader2, FileText, CheckCircle2, AlertCircle, Clock, Trash2, ExternalLink } from 'lucide-react';

export default function DocHistory({ config }) {
  const [snapshots, setSnapshots] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => { if (config?.id) load(); }, [config?.id]);

  const load = async () => {
    setLoading(true);
    try {
      const items = await base44.entities.ProjectDocumentSnapshot.filter({ configId: config.id }, '-created_date');
      setSnapshots(items);
    } catch (e) { console.error(e); }
    setLoading(false);
  };

  const remove = async (id) => {
    await base44.entities.ProjectDocumentSnapshot.delete(id);
    setSnapshots(prev => prev.filter(x => x.id !== id));
  };

  const STATUS_ICONS = {
    success: <CheckCircle2 className="w-4 h-4 text-green-400" />,
    failed:  <AlertCircle className="w-4 h-4 text-red-400" />,
    pending: <Clock className="w-4 h-4 text-amber-400" />,
  };

  const STATUS_COLORS = {
    success: 'text-green-400 bg-green-400/10 border-green-400/20',
    failed:  'text-red-400 bg-red-400/10 border-red-400/20',
    pending: 'text-amber-400 bg-amber-400/10 border-amber-400/20',
  };

  return (
    <div className="max-w-4xl space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold">Document History</h2>
          <p className="text-sm text-white/40 mt-0.5">Track all previously generated documents for this project configuration.</p>
        </div>
        <span className="text-xs text-white/30">{snapshots.length} records</span>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-12"><Loader2 className="w-6 h-6 animate-spin text-white/30" /></div>
      ) : snapshots.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 border border-white/5 rounded-2xl">
          <FileText className="w-10 h-10 text-white/15 mb-3" />
          <p className="text-sm text-white/30">No documents generated yet.</p>
          <p className="text-xs text-white/20 mt-1">Go to "Generate PDF" tab to create your first document.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {snapshots.map((s, i) => (
            <div key={s.id} className="glass-card rounded-2xl border border-white/8 p-5">
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-center gap-3">
                  {STATUS_ICONS[s.status] || STATUS_ICONS.pending}
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-bold text-white/80">Version {s.documentVersion || '1.0'}</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full border ${STATUS_COLORS[s.status] || STATUS_COLORS.pending}`}>
                        {s.status || 'pending'}
                      </span>
                      {i === 0 && <span className="text-xs px-2 py-0.5 rounded-full bg-cyan-400/10 border border-cyan-400/20 text-cyan-400">Latest</span>}
                    </div>
                    <div className="text-xs text-white/30 mt-0.5">
                      Generated by {s.generatedBy || '—'} · {s.generatedAt ? new Date(s.generatedAt).toLocaleString() : s.created_date ? new Date(s.created_date).toLocaleString() : '—'}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {s.pdfUrl && (
                    <a href={s.pdfUrl} target="_blank" rel="noopener noreferrer"
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-cyan-400/10 border border-cyan-400/20 text-cyan-400 rounded-lg text-xs hover:bg-cyan-400/20 transition-all">
                      <ExternalLink className="w-3 h-3" /> Open
                    </a>
                  )}
                  <button onClick={() => remove(s.id)} className="p-1.5 rounded-lg text-white/30 hover:text-red-400 hover:bg-red-400/10 transition-all">
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
              <div className="flex flex-wrap gap-4 mt-3 pt-3 border-t border-white/5">
                {[
                  { label: 'Sections', value: s.sectionCount },
                  { label: 'Screenshots', value: s.screenshotCount },
                  { label: 'Diagrams', value: s.diagramCount },
                  { label: 'Code Snippets', value: s.codeSnippetCount },
                ].map(item => (
                  <div key={item.label} className="text-center">
                    <div className="text-sm font-bold text-white/60">{item.value ?? '—'}</div>
                    <div className="text-xs text-white/25">{item.label}</div>
                  </div>
                ))}
                {s.notes && <div className="ml-auto text-xs text-white/25 italic self-center">{s.notes}</div>}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}